//description html
const descrition = {
    "Fitoftora_fase1_colonización": ['<h2>Fitoftora fase1 Colonización</h2>','<div><span>La fase 1 de la enfermedad se denomina "Colonización". Esta fase se caracteriza por la invasión inicial del hongo en el fruto del cacao</span><br><b>Descripción:</b><br><ul><li>El hongo Moniliophthora roreri se establece en el tejido del fruto del cacao, generalmente a través de heridas o aberturas naturales.</li><li>Durante esta fase, los síntomas visibles pueden ser mínimos, pero el hongo empieza a desarrollarse dentro del fruto.</li></ul><br><b>Tratamientos para la Fase de Colonización:</b><br><b>Manejo Cultural:</b><br><ul><li><span>Podas Sanitarias:</span> Elimina y destruye los frutos infectados y restos vegetales del suelo para reducir la fuente de inóculo.</li><li><span>Control de Sombra:</span> Mantén un nivel adecuado de sombra para reducir la humedad relativa y mejorar la circulación del aire.</li><li><span>Mantenimiento de Plantaciones:</span> Mantén las plantaciones limpias y bien mantenidas para reducir las condiciones favorables para el hongo.</li></ul><b>Manejo Químico:</b><br><ul><li><span>Fungicidas:</span> Aplica fungicidas autorizados de manera preventiva o al inicio de la colonización. Algunos fungicidas efectivos pueden incluir productos a base de cobre o triazoles.</li><li><span>Rotación de Fungicidas:</span> Para evitar la resistencia del hongo, rota diferentes tipos de fungicidas y sigue las recomendaciones del fabricante.</li></ul><b>Manejo Biológico:</b><br><ul><li><span>Antagonistas Microbianos:</span> Utiliza microorganismos benéficos que compiten con el hongo patógeno. Ejemplos incluyen Trichoderma spp. y Bacillus subtilis, que pueden aplicarse a los frutos y al suelo.</li><li><span>Extractos Vegetales:</span> Algunos extractos de plantas tienen propiedades antifúngicas y pueden ser utilizados como parte de un manejo integrado.</li></ul></div>'],


    "Fitoftora_fase2_Reproducción": ["<h2>Fitoftora fase2 Reproducción</h2>",'<div><span>La fase 2 de la enfermedad se denomina "Reproducción". Esta fase es crucial en el ciclo de vida del hongo Moniliophthora roreri y se caracteriza por la producción y liberación de esporas.</span><br><b>Descripción:</b><br><ul><li><span>En esta fase, el hongo produce estructuras de reproducción (esporangios) que se desarrollan en la superficie del fruto infectado.</span></li><li><span>Los esporangios liberan esporas que se dispersan a través del viento, el agua y el contacto directo, propagando la enfermedad a otros frutos.</span></li></ul><b>Tratamientos para la Fase de Reproducción:</b><br><b>Manejo Cultural:</b><br><ul><li><span>Eliminación de Frutos Infectados:</span> Es crucial retirar y destruir los frutos infectados antes de que se produzcan las esporas. Los frutos deben ser enterrados o quemados lejos de la plantación para evitar la dispersión de esporas.</li><li><span>Higiene en el Campo:</span> Mantener la limpieza del campo es vital. Esto incluye la recolección de restos de frutos y hojas caídas, que pueden ser fuentes de inóculo.</li></ul><b>Control Químico:</b><br><ul><li><span>Aplicación de Fungicidas:</span> Durante esta fase, es fundamental aplicar fungicidas de manera preventiva y curativa para reducir la producción de esporas. Fungicidas a base de cobre, azufre y otros agentes específicos contra hongos pueden ser efectivos.</li><li><span>Programas de Pulverización:</span> Sigue un programa de pulverización regular basado en las condiciones ambientales y la incidencia de la enfermedad. Es esencial aplicar fungicidas antes de que se produzcan lluvias, ya que estas facilitan la dispersión de esporas.</li></ul><b>Control Biológico:</b><br><ul><li><span>Uso de Microorganismos Antagonistas:</span> Introducir microorganismos benéficos como Trichoderma spp. y Bacillus subtilis que inhiben el crecimiento y reproducción del hongo patógeno.</li><li><span>Biopesticidas:</span> Aplicar productos biológicos y extractos de plantas con propiedades antifúngicas que pueden reducir la producción de esporas.</li></ul></div>'],
    

    "cacao_sano": ["<h2>cacao_sano</h2>",'<div><span>Un cacao sano es un fruto que se desarrolla adecuadamente sin mostrar signos de enfermedades, plagas o deficiencias nutricionales. Aquí tienes una descripción detallada de las características de un cacao sano:</span><br><b>Características de un Cacao Sano:</b><br><b>Apariencia del Fruto:</b><ul><li><span>Color Uniforme: El fruto del cacao, conocido como mazorca, debe tener un color uniforme acorde a su variedad y estado de madurez. Esto puede variar desde verde para frutos inmaduros hasta amarillo, rojo o naranja para frutos maduros, dependiendo de la variedad.</span></li><li><span>Superficie Lisa: La cáscara del fruto debe ser lisa y sin manchas, cicatrices, o lesiones. No debe haber presencia de manchas blancas, amarillas, o negras que podrían indicar enfermedades como la Moniliasis o la Escoba de Bruja.</span></li></ul><b>Tamaño y Forma:</b><ul><li><span>Desarrollo Completo: El fruto debe tener un tamaño y forma adecuada para su variedad, indicando un desarrollo completo y saludable. Las mazorcas deformadas o subdesarrolladas pueden indicar problemas nutricionales o estrés en la planta.</span></li><li><span>Simetría: Las mazorcas deben ser simétricas, sin abultamientos ni deformidades.</span></li></ul><b>Textura:</b><ul><li><span>Firmeza: La cáscara debe ser firme al tacto, sin partes blandas o necrosadas que podrían indicar pudrición o infecciones fúngicas.</span></li><li><span>Sin Grietas: La superficie no debe tener grietas ni aberturas que puedan servir como puntos de entrada para patógenos.</span></li></ul></div>']


};
