//description html
const descrition = {
    "pod_borer": '<p>La enfermedad que mencionas, "pod borer" (tal vez te refieras al "cacao pod borer"), en realidad no es una enfermedad, sino una plaga que afecta al cacao. Esta plaga es causada por insectos, específicamente por la polilla del cacao (Conopomorpha cramerella) y otras especies relacionadas. Estos insectos dañan los frutos del cacao, perforando los capullos y las cáscaras de las vainas para depositar sus huevos. Una vez que las larvas eclosionan, se alimentan del tejido del cacao dentro de las vainas, lo que puede causar daños significativos a la producción.<br>El cacao pod borer es una de las plagas más importantes y devastadoras para los productores de cacao, ya que puede provocar pérdidas significativas en la cosecha y reducir la calidad de los granos de cacao. Los métodos de control de esta plaga suelen incluir el uso de pesticidas, la eliminación de vainas infectadas y la implementación de prácticas agronómicas para reducir la población de insectos, como la poda adecuada y el manejo integrado de plagas.<br>El cacao pod borer es una de las plagas más importantes y devastadoras para los productores de cacao, ya que puede provocar pérdidas significativas en la cosecha y reducir la calidad de los granos de cacao. Los métodos de control de esta plaga suelen incluir el uso de pesticidas, la eliminación de vainas infectadas y la implementación de prácticas agronómicas para reducir la población de insectos, como la poda adecuada y el manejo integrado de plagas.<br>Es crucial para los productores de cacao monitorear y controlar la presencia de esta plaga para proteger sus cultivos y asegurar una producción saludable de cacao.</p>',


    "healthy": '<p>Un cacao en buen estado muestra un árbol robusto y vital, con hojas de un verde vibrante y saludable, sin señales de enfermedad o daño. Sus frutos se distribuyen de manera uniforme a lo largo de las ramas, exhibiendo vainas de forma regular y color verde brillante, sin evidencia de daño físico o de ataques de plagas. Al abrir una vaina, revela una pulpa blanca o ligeramente rosada, fresca y jugosa, con un aroma dulce y agradable. Las semillas de cacao dentro de la pulpa están bien formadas, con un color uniforme que oscila entre marrón claro y oscuro, sin mostrar signos de deterioro o daño. En conjunto, un cacao sano se caracteriza por su vigorosidad, uniformidad y calidad de sus frutos, lo que asegura una producción óptima de cacao de alta calidad.Frutos uniformes: Los frutos del cacao en un árbol sano se desarrollan de manera uniforme a lo largo de las ramas. Las vainas tienen una forma característica, ya sea ovalada o alargada, y tienen un color verde brillante y uniforme.<br>Vainas sin daños visibles: Las vainas del cacao sano están libres de daños visibles, como perforaciones, manchas o signos de descomposición. Tienen una textura firme al tacto y no muestran signos de enfermedad o infestación por plagas.<br>Pulpa jugosa y aromática: Al abrir una vaina de cacao sana, se revela una pulpa blanca y jugosa que envuelve las almendras (semillas) del cacao. Esta pulpa es de color blanco o ligeramente rosado y tiene un aroma dulce y agradable.<br>Almendras de cacao sanas: Las almendras de cacao en un fruto sano tienen un color marrón claro a marrón oscuro uniforme y están libres de signos de enfermedad, daño por plagas o descomposición. Tienen un aspecto brillante y una textura firme y densa.</p>',



    
    "black_pod_rot": '<p>La "black pod rot" (podredumbre de la vaina negra) es una enfermedad común y destructiva que afecta al cacao. Es causada por varios hongos del género Phytophthora, especialmente Phytophthora palmivora y Phytophthora megakarya. Estos hongos prosperan en condiciones de alta humedad y temperaturas cálidas, lo que hace que sean un problema significativo en las regiones tropicales donde se cultiva el cacao.<br>Los síntomas típicos de la black pod rot incluyen manchas húmedas y oscuras en las vainas de cacao, que luego se expanden y se vuelven negras a medida que la enfermedad avanza. Estas manchas pueden estar cubiertas por un moho blanco o rosado en condiciones de alta humedad. Con el tiempo, las vainas infectadas se vuelven blandas y húmedas, y pueden colapsar, provocando la pérdida de la cosecha.<br>El control de la black pod rot generalmente implica una combinación de medidas preventivas y de manejo. Esto puede incluir prácticas culturales como la poda adecuada de árboles, el manejo de la sombra, el drenaje del suelo y la eliminación o destrucción de vainas infectadas. Además, el uso de fungicidas puede ser necesario para controlar la propagación de la enfermedad en situaciones graves.<br>Es fundamental para los productores de cacao estar atentos a los síntomas de la black pod rot y tomar medidas rápidas para controlar su propagación, ya que puede causar pérdidas significativas en la producción si no se maneja adecuadamente.</p>'
};
